
export const LOGIN_ACTIONS = {
    LOGIN_REQUEST: ' LOGIN_REQUEST',
    LOGIN_RESPONSE: ' LOGIN_RESPONSE',
    LOGIN_ERROR: 'LOGIN_ERROR'
};


export const GET_DATA_ACTIONS = {
    GET_DATA_REQUEST: ' GET_DATA_REQUEST',
    GET_DATA_RESPONSE: ' GET_DATA_RESPONSE',
    GET_DATA_ERROR: 'GET_DATA_ERROR'
};

export const CREATE_USER_ACTIONS = {
    CREATE_USER_REQUEST: ' CREATE_USER_REQUEST',
    CREATE_USER_RESPONSE: ' CREATE_USER_RESPONSE',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR'
};
export const DELETE_USER_ACTIONS = {
    DELETE_USER_REQUEST: ' DELETE_USER_REQUEST',
    DELETE_USER_RESPONSE: ' DELETE_USER_RESPONSE',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR'
};